.github/ci/generate-news-feed.js, .github/pull_request_template.md, README.md, package-lock.json, package.json
Fix [#691](https://github.com/hlxsites/vg-volvotrucks-us/issues/691)
##URL for testing:
- https://691-new-volvo--volvotrucks-na--aemsites.hlx.page/
Test URLs:
- After: https://691-new-volvo--volvotrucks-us--volvogroup.aem.page/
=> New Volvo Trucks infra changes #691

.github/workflows/unpublish-notifier.yaml
Fix #755
- https://755-search-migration-unpublish--volvotrucks-na--aemsites.hlx.page/
Other test URLs:
Other markets:
Canada:
- After: https://755-search-migration-unpublish--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://755-search-migration-unpublish--volvotrucks-mx--volvogroup.aem.page/
=> 755 update unpublish gh-action

.github/workflows/old-publish-notifier.yaml, .github/workflows/old-unpublish-notifier.yaml
Fix #755
- https://755-search-migration-old-connector--volvotrucks-na--aemsites.hlx.page/
Other test URLs:
Other markets:
Canada:
- After: https://<branch>--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://<branch>--volvotrucks-mx--volvogroup.aem.page/
=> 755 search migration old connector

head.html
Fix #797
- https://797-ios-loading-fix--volvotrucks-na--aemsites.hlx.page/
=> Revert change #797

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/new_feature.yml, .github/ISSUE_TEMPLATE/technical-debt.yml, blocks/v2-truck-lineup/v2-truck-lineup.js, scripts/common.js, tools/fgrep-attr/fgrep.js
Fix #105
The missing buttons on the sidekick should be available now for the 3 websites (US, CA and MX):
=> Cleanup configs #105 

blocks/footer/footer.css
Fix #36 
- After: https://36-VT-CA-defects--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- After: https://36-VT-CA-defects--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://36-VT-CA-defects--volvotrucks-mx--volvogroup.aem.page/
=> Footer links alignement issue #36

blocks/footer/footer.css, blocks/key-facts/key-facts.css, blocks/v2-article-search/v2-article-search.css, blocks/v2-article-search/v2-article-search.js, blocks/v2-key-facts/v2-key-facts.css, blocks/v2-key-facts/v2-key-facts.js, package-lock.json, package.json, templates/v2-magazine/v2-magazine.js
- After: https://release-26--volvotrucks-us--volvogroup.aem.page/
=> Release 26

common/modal/modal.js
Fix #143
- Before: https://main--volvotrucks-us--volvogroup.aem.page/trucks/powertrain/d13tc/
- After: https://143-hotfix-hero-yt-link--volvotrucks-us--volvogroup.aem.page/trucks/powertrain/d13tc/
=> Fix hero with youtube video link #143

blocks/dealer-locator/dealer-locator.css, blocks/dealer-locator/sidebar-maps.js, blocks/eloqua-form/forms/ContactUsVolvo.html, blocks/eloqua-form/forms/ExceedingExpectationsSignup.html, blocks/eloqua-form/forms/VNR_Electric_CU.html, blocks/eloqua-form/forms/copyOfTruck19Q3EMTeaserSignUpFR-1582126715298.html, blocks/eloqua-form/forms/copyfuelefficient-637860630969151756.html, blocks/eloqua-form/forms/event-from.html, blocks/eloqua-form/forms/servicesubscriptions.html, blocks/eloqua-form/forms/turbo-calculator-form.html, styles/styles.css, tools/tagger/tagger.css
Fix #56
- After: https://56-change-arial-to-notosans--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- After: https://56-change-arial-to-notosans--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://56-change-arial-to-notosans--volvotrucks-mx--volvogroup.aem.page/
=> Swap Arial to "Noto Sans" font #56

blocks/v2-video/v2-video.js
Fix #133
- After: https://133-bug-v2-video-on-mobile--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- After: https://133-bug-v2-video-on-mobile--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://133-bug-v2-video-on-mobile--volvotrucks-mx--volvogroup.aem.page/
=> V2 Video on Mobile #133

blocks/magazine-articles/magazine-articles.js, blocks/related-articles/related-articles.js, blocks/search/autosuggest.js, blocks/search/search.js, blocks/v2-article-cards/v2-article-cards.js, blocks/v2-article-search/v2-article-search.js, blocks/v2-stories-carousel/v2-stories-carousel.js, scripts/search-api.js, scripts/services/magazine.service.js
Fix #136
Magazine Articles
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/magazine-articles
- After: https://136-connect-graphql-magazine-blocks--volvotrucks-us--volvogroup.aem.page/block-library/blocks/magazine-articles
Related articles (at the bottom of the page)
- Before: https://main--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-magazine/25-years-of-driving-progress/
- After: https://136-connect-graphql-magazine-blocks--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-magazine/25-years-of-driving-progress/
V2 Article Cards
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-article-cards
- After: https://136-connect-graphql-magazine-blocks--volvotrucks-us--volvogroup …
=> Connect GraphQL to magazine related blocks #136

blocks/dealer-locator/dealer-locator.css, blocks/dealer-locator/sidebar-maps.js, blocks/eloqua-form/forms/ContactUsVolvo.html, blocks/eloqua-form/forms/ExceedingExpectationsSignup.html, blocks/eloqua-form/forms/VNR_Electric_CU.html, blocks/eloqua-form/forms/copyOfTruck19Q3EMTeaserSignUpFR-1582126715298.html, blocks/eloqua-form/forms/copyfuelefficient-637860630969151756.html, blocks/eloqua-form/forms/event-from.html, blocks/eloqua-form/forms/servicesubscriptions.html, blocks/eloqua-form/forms/turbo-calculator-form.html, blocks/magazine-articles/magazine-articles.js, blocks/related-articles/related-articles.js, blocks/search/autosuggest.js, blocks/search/search.js, blocks/v2-article-cards/v2-article-cards.js, blocks/v2-article-search/v2-article-search.js, blocks/v2-stories-carousel/v2-stories-carousel.js, blocks/v2-video/v2-video.js, package-lock.json, package.json, scripts/search-api.js, scripts/services/magazine.service.js, styles/styles.css, tools/tagger/tagger.css
- After: https://release-27--volvotrucks-us--volvogroup.aem.page/
=> Release 27

blocks/v2-media-with-text/v2-media-with-text.css, blocks/v2-media-with-text/v2-media-with-text.js, scripts/video-helper.js, styles/styles.css
Fix #29
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-media-with-text
- After: https://29-media-with-text-video--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-media-with-text
It's the last variant on the page.
=> V2 Media with Text - Video with Poster #29

404.html, blocks/dealer-locator/sidebar-maps.js, blocks/get-an-offer/get-an-offer.js, blocks/key-facts/key-facts.js, blocks/v2-forms/v2-forms.js, scripts/aem.js, scripts/scripts.js, scripts/video-helper.js
Fix #107
- After: https://107-js-errors--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- After: https://107-js-errors--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://107-js-errors--volvotrucks-mx--volvogroup.aem.page/
=> Volvo Trucks NA Javascript errors #107

404.html, blocks/dealer-locator/sidebar-maps.js, blocks/get-an-offer/get-an-offer.js, blocks/key-facts/key-facts.js, blocks/v2-forms/v2-forms.js, blocks/v2-media-with-text/v2-media-with-text.css, blocks/v2-media-with-text/v2-media-with-text.js, constants.json, package-lock.json, package.json, scripts/aem.js, scripts/delayed.js, scripts/scripts.js, scripts/video-helper.js, styles/styles.css
- After: https://release-29--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- After: https:///release-29--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https:///release-29--volvotrucks-mx--volvogroup.aem.page/
=> Release 29

head.html, scripts/common.js
Fix #151
- After: https://151-fix-favicon--volvotrucks-us--volvogroup.aem.page/
=> Fav icon not appearing on BING search #151

blocks/v2-media-with-text/v2-media-with-text.css
Fix #205
- Before: https://main--volvotrucks-us--volvogroup.aem.page/trucks/vnl/#safety
- After: https://205-media-text-spacing--volvotrucks-us--volvogroup.aem.page/trucks/vnl/#safety
=> V2 media w/ text block formatting and spacing is incorrect #205

blocks/v2-content-carousel/v2-content-carousel.css, blocks/v2-content-carousel/v2-content-carousel.js
Fix #218
- Before: https://main--volvotrucks-us--volvogroup.aem.page/trucks/vnr/all-new-vnr/exterior
- After: https://218-content-carousel-text--volvotrucks-us--volvogroup.aem.page/trucks/vnr/all-new-vnr/exterior
=> V2 Content Carousel - Adjustment to text displayed below images #218

blocks/v2-media-with-text/v2-media-with-text.css, blocks/v2-media-with-text/v2-media-with-text.js
Fix #211
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/alan/v2-media-with-text
- After: https://211-media-text-title-size--volvotrucks-us--volvogroup.aem.page/drafts/alan/v2-media-with-text
=> [V2 Media with Text] - Option to change title text size #211

blocks/v2-article-search/v2-article-search.js, scripts/services/magazine.service.js
Fix #232
- After: https://232-hotfix-magazine--volvotrucks-us--volvogroup.aem.page/
=> Stories from the road section not appearing #232

blocks/v2-text/v2-text.css, blocks/v2-text/v2-text.js
Fix #212
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-text
- After: https://212-v2-text-title-small-mod--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-text
=> FR: V2 Text - Option to change text title to a smaller size #212

404.html, blocks/fragment/fragment.js
Fix #59
- Before: https://main--volvotrucks-us--volvogroup.aem.page/some-invalid-page
- After: https://59-localised-error--volvotrucks-us--volvogroup.aem.page/some-invalid-page
Other markets:
Canada:
- Before EN: https://main--volvotrucks-ca--volvogroup.aem.page/en-ca/some-invalid-page
- Before FR: https://main--volvotrucks-ca--volvogroup.aem.page/fr-ca/some-invalid-page
- After EN: https://59-localised-error--volvotrucks-ca--volvogroup.aem.page/en-ca/some-invalid-page
- After FR: https://59-localised-error--volvotrucks-ca--volvogroup.aem.page/fr-ca/some-invalid-page
Mexico:
- Before: https://main--volvotrucks-mx--volvogroup.aem.page/some-invalid-page
- After: https://59-localised-error--volvotrucks-mx--volvogroup.aem.page/some-invalid-page
=> NFR: 404 Page Localization - Primary Markets Volvo #59

blocks/v2-dealer-locator-teaser/v2-dealer-locator-teaser.css, blocks/v2-dealer-locator-teaser/v2-dealer-locator-teaser.js
Fix #217
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-dealer-locator-teaser
- After: https://217-dealer-teaser-mod--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-dealer-locator-teaser
=> FR: V2 dealer locator teaser - Layout enhancement #217

blocks/engine-specifications/engine-specifications.css, blocks/engine-specifications/engine-specifications.js, blocks/engine-specifications/performance-chart.js
Fix #225
- Before: https://main--volvotrucks-us--volvogroup.aem.page/trucks/powertrain/v2/d11/
- After: https://225-adjust-perf-chart--volvotrucks-us--volvogroup.aem.page/trucks/powertrain/v2/d11/
=> FR: Adjust performance specifications chart for the engine ratings #225

blocks/v2-hero-reveal/v2-hero-reveal.css, blocks/v2-hero-reveal/v2-hero-reveal.js, blocks/v2-hero/v2-hero.js, blocks/v2-livestream-embed/v2-livestream-embed.js, blocks/v2-video/v2-video.js, common/modal/modal.css, common/modal/modal.js, scripts/video-helper.js
Fix #197 
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/alexis/reveal/v2-hero-reveal
- After: https://197-reveal-integration--volvotrucks-us--volvogroup.aem.page/drafts/alexis/reveal/v2-hero-reveal
=> FR: Restream integration (embed web player) #197

blocks/v2-forms/v2-forms.js
_V2 Forms_ block is looking for the 1st form on the page. This could be a problem on pages with more than 1 `form` element.
To fix that, this update encapsulates the `form` element inside the _V2 Forms_ block to let the author add any amount of this block or other forms.
#
Fix #240 
- After: https://240-magazine-subscription-error--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-stories/
=> Magazine subscription Submission pop-up message error #240

blocks/v2-forms/v2-forms.js, blocks/v2-hero-reveal/v2-hero-reveal.js, package-lock.json, package.json, templates/v2-magazine/v2-magazine.js
- After: https://release-32--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- After: https://release-32--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://release-32--volvotrucks-mx--volvogroup.aem.page/
=> Release 32

blocks/v2-custom-form/v2-custom-form.css, blocks/v2-custom-form/v2-custom-form.js, common/custom-dropdown/custom-dropdown.css, common/custom-dropdown/custom-dropdown.js, styles/styles.css
This update adds better feedback for the `v2-custom-form` block to show the _error_, _hover_ and _focus_ state design
- This update Fix a little issue to the `v2-custom-form` block to show correctly a placeholder as selected text
- The focus and hover states both use the same blue for consistency instead of the designs
- also I push the commits in a way that separates the custom dropdown enhancement, the JSDocs update, the error feedback and the focus/hover states
#
Fix #230
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/v2-feedback-form-demo
- After: https://230-form-feedback-for-mcae--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/v2-feedback-form-demo
=> FR: Form Layout for MCAE - VT #230

scripts/video-helper.js
Fix #310
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-video
- After: https://310-video-playback-ios--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-video
=> Custom playback button not working on iOS #310 Open

blocks/v2-inpage-navigation/v2-inpage-navigation.js, scripts/scripts.js
Fix #275
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/alan/
- After: https://275-in-page-nav-glitch--volvotrucks-us--volvogroup.aem.page/drafts/alan/
=> Glitchy interaction on page navigation for VNR PDP #275

scripts/delayed.js, scripts/scripts.js, scripts/video-helper.js
Fix #306
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/alan/v2-video-improve-loading
- After: https://306-improve-loading-videos--volvotrucks-us--volvogroup.aem.page/drafts/alan/v2-video-improve-loading
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/alan/blocks-with-video-test
- After: https://306-improve-loading-videos--volvotrucks-us--volvogroup.aem.page/drafts/alan/blocks-with-video-test
=> Spike: Improve the loading of AEM asset videos and the Video.js library #306

blocks/v2-custom-form/v2-custom-form.css, blocks/v2-custom-form/v2-custom-form.js
Fix #320
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/shomps/form/vcc-ride-and-drive-waiver
- After: https://320-custom-form-centered--volvotrucks-us--volvogroup.aem.page/drafts/shomps/form/vcc-ride-and-drive-waiver
Library:
- https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-custom-form
- https://320-custom-form-centered--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-custom-form
=> FR: [VTNA] Centering the V2 Custom Form content #320

blocks/v2-custom-form/v2-custom-form.js
To add more form validations, in the xlsx form config file, 3 more columns need to be added, such as Pattern, Min & Max (case sensitive btw)
Same as MT's PR for issue 260
#
Fix #327
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/v2-2-columns-form-demo
- After: https://327-form-fields-validations--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/v2-2-columns-form-demo
- Before: https://main--volvotrucks-us--volvogroup.aem.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-custom-form&index=0
- After: https://327-form-fields-validations--volvotrucks-us--volvogroup.aem.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-custom-form&index=0
=> FR: MCAE form fields validations - VT #327

blocks/v2-custom-form/v2-custom-form.js, styles/styles.css
Fix #312
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-custom-form
- After: https://312-honeypot-field--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-custom-form
=> FR: Add honeypot field to V2 Custom Form block detect bot submission #312

blocks/search/autosuggest.js, blocks/v2-custom-form/v2-custom-form.css, blocks/v2-custom-form/v2-custom-form.js, common/modal/modal.js, package-lock.json, package.json, scripts/common.js, scripts/scripts.js, scripts/search-api.js, scripts/video-helper.js, styles/styles.css
- After: https://release-36--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- After: https://release-36--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://release-36--volvotrucks-mx--volvogroup.aem.page/
=> Release 36

.github/workflows/publish-notifier.yaml
revert notify connector job
Fix #89
URL for score testing:
- After: https://89-gh-action-notification--volvotrucks-us--volvogroup.aem.page/
=> 89 gh action notification

.github/workflows/publish-notifier.yaml
Revert all changes to leave it as before
Fix #89
- After: https://89-gh-email-on-error--volvotrucks-us--volvogroup.aem.page/
=> Spike: Update GitHub Actions - Notifications (2 of 4) #89

.github/workflows/old-publish-notifier.yaml, .github/workflows/publish-notifier.yaml
- After: https://89-gh-email-on-error--volvotrucks-us--volvogroup.aem.page/
=> updates old connector to test email on error

blocks/search/autosuggest.js, blocks/search/templates.js, scripts/search-api.js
Fix #166
Test URLs:
Before: https://main--volvotrucks-us--volvogroup.aem.page/search-results
After: https://166-search-suggest--volvotrucks-us--volvogroup.aem.page/search-results
Other markets:
Canada:
Before: https://main--volvotrucks-ca--volvogroup.aem.page/en-ca/search-results
After: https://166-search-suggest--volvotrucks-ca--volvogroup.aem.page/en-ca/search-results
Mexico (search not available in mexico yet):
=> FR: Inconsistency in search suggestions #166

scripts/delayed.js
Add the cookie check inside a function for it to run also at the begging.
Fix #401
- After: https://401-cookies--volvotrucks-us--volvogroup.aem.page/
=> Spike: Investigate High Volume of "Direct" Traffic in GA for Volvo Trucks Website #401

.github/workflows/old-publish-notifier.yaml
Fix #190
- After: https://190-slack-notifications--volvotrucks-us--volvogroup.aem.page/
=> FR: Update GitHub Actions - Notifications (3 of 4) #190

blocks/v2-media-with-text/v2-media-with-text.js, scripts/common.js
Fix #375
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-media-with-text
- After: https://375-v2-media-text-video--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-media-with-text
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/video/aem-video-demo
- After: https://375-v2-media-text-video--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/video/aem-video-demo
=> Bug: V2 Media with text - Video [AEM assets link] is not working #375

common/modal/modal.css
Fix #337 
- Before: https://main--volvotrucks-us--volvogroup.aem.page/trucks/all-new-vnr/#safety
- After: https://337-fix-title-font-size-v2-text--volvotrucks-us--volvogroup.aem.page/trucks/all-new-vnr/#safety
=> Bug: Font size from "Safety" section

blocks/search/autosuggest.js, blocks/v2-article-search/v2-article-search.css, blocks/v2-article-search/v2-article-search.js, placeholder.json
Fix #60 
- Before: https://main--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-stories/?search=&category=&topic=&truck=
- After: https://60-autocomplete-magazine-search--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-stories/?search=&category=&topic=&truck=
=> FR: Autocomplete Magazine Search

blocks/magazine-articles/magazine-articles.js, blocks/press-releases/press-releases.css, blocks/press-releases/press-releases.js, blocks/search/autosuggest.js, blocks/v2-article-search/v2-article-search.css, blocks/v2-article-search/v2-article-search.js, blocks/v2-custom-form/v2-custom-form.js, common/modal/modal.css, package-lock.json, package.json, placeholder.json, scripts/search-api.js, scripts/services/press-release.service.js
- After: https://release-41--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- After: https://release-41--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://release-41--volvotrucks-mx--volvogroup.aem.page/
=> Release 41

blocks/v2-media-with-text/v2-media-with-text.css
Fix #336 
- Before: https://main--volvotrucks-us--volvogroup.aem.page/trucks/all-new-vnr/#safety
- After: https://336-wrong-colors-in-media-text--volvotrucks-us--volvogroup.aem.page/trucks/all-new-vnr/#safety
=> Bug: Font color Bugs from "Safety" section

blocks/v2-truck-lineup/v2-truck-lineup.css, blocks/v2-truck-lineup/v2-truck-lineup.js
Fix #386 
- Before: https://main--volvotrucks-us--volvogroup.aem.page/trucks/all-new-vnr/#models
- After: https://386-remove-inscription-from-pdp--volvotrucks-us--volvogroup.aem.page/trucks/all-new-vnr/#models
=> CR: Remove inscription from product specs

blocks/dealer-locator/sidebar-maps.js
Fix #418
- Before: https://main--volvotrucks-us--volvogroup.aem.page/find-a-dealer/
- After: https://418-distance-calc--volvotrucks-us--volvogroup.aem.page/find-a-dealer/
Other markets:
Canada - english:
- Before: https://main--volvotrucks-ca--volvogroup.aem.page/en-ca/find-a-dealer/
- After: https://418-distance-calc--volvotrucks-ca--volvogroup.aem.page/en-ca/find-a-dealer/
Canada - french:
- Before: https://main--volvotrucks-ca--volvogroup.aem.page/fr-ca/find-a-dealer/
- After: https://418-distance-calc--volvotrucks-ca--volvogroup.aem.page/fr-ca/find-a-dealer/
Mexico:
- Before: https://main--volvotrucks-mx--volvogroup.aem.page/find-a-dealer/
- After: https://418-distance-calc--volvotrucks-mx--volvogroup.aem.page/find-a-dealer/
=> Bug: Web version of the Dealer Locator shows incorrect distance #418

blocks/v2-masonry-grid/v2-masonry-grid.css, blocks/v2-section-header/v2-section-header.css
Fix #385
- Before: https://main--volvotrucks-us--volvogroup.aem.page/trucks/all-new-vnr/
- After: https://385-adjust-padding-on-pdp--volvotrucks-us--volvogroup.aem.page/trucks/all-new-vnr/
=> CR: Adjust padding on the PDP section

.github/workflows/unpublish-notifier.yaml
Fix #431
- After: https://427-gh-action-fix--volvotrucks-us--volvogroup.aem.page/
=> FR: Restrict Resource Publishing and Update Path Handling in publish-notifier.yaml #431

blocks/press-releases/press-releases.js, blocks/v2-article-cards/v2-article-cards.js, common/pagination/pagination.js
Fix #437 
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/press-releases
- After: https://437-dynamic-pagination--volvotrucks-us--volvogroup.aem.page/block-library/blocks/press-releases
- Before: https://main--volvotrucks-us--volvogroup.aem.page/news-and-stories/press-releases/
- After: https://437-dynamic-pagination--volvotrucks-us--volvogroup.aem.page/news-and-stories/press-releases/
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-article-cards
- After: https://437-dynamic-pagination--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-article-cards
Other markets:
Canada:
- Before: https://main--volvotrucks-ca--volvogroup.aem.page/en-ca/news-and-stories/press-releases/
- After: …
=> FR: Implement dynamic pagination for press releases and magazine articles #437

blocks/vin-number/vin-number.js, placeholder.json
Test VIN number **3CET2W420P5209578**
Fix #497
- Before: https://main--volvotrucks-us--volvogroup.aem.page/recalls/
- After: https://497-vin-precautions--volvotrucks-us--volvogroup.aem.page/recalls/
**NOTE:**
API loads different values for 'dev' and 'prod'. You WONT be able to see this unless its running in local (at least the VIN numbers I tried). 
I'm leaving screenshots from what I have currently, FR translation was done by me; please advise @alan-le-bihan if this does not make sense:
=> Transport Canada: Add "Precautions to Minimize Risk“ [Volvo-English] #497

blocks/vin-number/vin-number.js, placeholder.json
Fix #498
- Before: https://main--volvotrucks-us--volvogroup.aem.page/recalls/
- After: https://498-recall-date--volvotrucks-us--volvogroup.aem.page/recalls/
=> Transport Canada: Add "Remedy Availability“ [Volvo-English] #498

blocks/vin-number/vin-number.js, placeholder.json
Fix #496
- Before: https://main--volvotrucks-us--volvogroup.aem.page/recalls/
- After: https://496-issue-date--volvotrucks-us--volvogroup.aem.page/recalls/
=> Transport Canada: Add "Transport Canada Issue Date“ [Volvo-English] #496
