.github/workflows/publish-notifier.yaml, .github/workflows/unpublish-notifier.yaml
Fix #749
- https://749-search-task-4-of-4--volvotrucks-na--aemsites.hlx.page/
Other test URLs:
Other markets:
Canada:
- After: https://<branch>--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://<branch>--volvotrucks-mx--volvogroup.aem.page/
=> 749 - handle index names in gh action client_payload.path

scripts/video-helper.js
Fix #9
`videojsConfig` has been changed so that videos have controls and can be set with sound from the `metadata` block in the page. If there is a field with `Video sound | on` (check sharepoint) the videos in that page should play with sound.
- https://9-videos-no-sound--volvotrucks-na--aemsites.hlx.page/drafts/shomps/video-metadata
Other test URLs:
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/shomps/video-metadata
Other markets:
Canada:
- After: https://9-videos-no-sound--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://9-videos-no-sound--volvotrucks-mx--volvogroup.aem.page/
=> Controls and sound configuration added to video #9

.github/pull_request_template.md, tools/sidekick/config.json, tools/sidekick/library.html
Extra: Also changed a bit the PR format
Fix #109
- After: https://109-library-fix--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- After: https://109-library-fix--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://109-library-fix--volvotrucks-mx--volvogroup.aem.page/
=> Library link changes #109

blocks/v2-article-search/v2-article-search.css, blocks/v2-article-search/v2-article-search.js, placeholder.json, scripts/search-api.js
Fix #33
This block can be added above a magazine article and this will open in a new tab on the magazine's main page with the URL updated with the topic selected from the dropdown `All Topics` list and the search input also opens with the search term.
if the user goes back to the article page, the dropdown keeps the bullet selected (unless the tab is closed) and if something is searched, the input is reset
2 variants can be added: _black_ and _gray_, if both are used together, gray overwrite the black variant
- https://main--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/magazine/magazine-article-demo
- Before: https://33-fe-magazine-article--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/magazine/magazine-article-demo
=> FE magazine article search #33

head.html, styles/styles.css
This fix removes a minor bug related to how the Noto font is imported. now is added to the `head.html`
Fix #153
- After: https://153-bug-fix-fonts-loading--volvotrucks-us--volvogroup.aem.page/
=> add import Noto font to the head & minor font adjustments #153

blocks/v2-article-search/v2-article-search.css
add for all viewports a z-index to push to front the topics dropdown, not only in desktop
Fix #160
- After: https://160-magazine-filters-drop-down--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-stories/
=> add a z-index for all viewports #160

blocks/v2-article-cards/v2-article-cards.js
The test URL uses the dev search URL. For some reason that makes that the cards are missing
like this:
So, for test purposes, it's needed to use the devTools and mock the `isDevHost` value in the `search-api` as `true`
then it should look like this:
Fix #159
- After: https://159-blurry-images-overview-page--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-stories/
=> Bug: Blurry Images on Volvo Trucks Stories Overview Page #159

templates/v2-magazine/v2-magazine.js
The Hero added by the v2-magazine template got previously the tags from metadata `article:tag` metadata. Now it gets the values from the updated tags source: `article-category`, `topic` & `truck` instead of `article:tag`. Also, the tags are now sorted alphabetically.
#
Fix #161
- Before: https://main--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-stories/interior-amenities/
- After: https://161-magazine-template-metadata--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-stories/interior-amenities/
=> NFR: Update V2 Magazine template to gather the proper metadata #161

common/modal/modal.css
Video modal iframe now its height is responsive too based on the screen size
this also hides conditionally the _feedback_ and _cookie_ buttons
this is needed to go to PROD directly
#
Fix #255, #254 & #257
- After: https://255-video-modal-fully-visible--volvotrucks-us--volvogroup.aem.page/
=> FR: Ensure video in modal is fully visible #255 #254 #257

blocks/engine-specifications/engine-specifications.css, constants.json
This issue adapts the 'engine-performance' blocks to work with and without the redesign tab. In redesign pages, the background is set via 'section-metadata' block. There is an example of all versions below.
NOTE: In redesign times some adaptation to the block has been done and that is why you'll see it no 100% the same as in figma. Some margins, sizes and fonts have been set globally for redesign pages and I consider that this should be left compatible to V2 in that cases. No example of this redesigned block has been given as far as I know.
Fix #251
**V2 page + block with gray BG**
- Before: https://main--volvotrucks-us--volvogroup.aem.page/trucks/powertrain/v2/d11/#specs
- After: https://251-styling-charts--volvotrucks-us--volvogroup.aem.page/trucks/powertrain/v2/d11/#spe …
=> FR: Update style for the chart engine ratings #251

blocks/v2-article-cards/v2-article-cards.css, blocks/v2-article-cards/v2-article-cards.js, blocks/v2-article-search/v2-article-search.js, constants.json, scripts/search-api.js, scripts/services/magazine.service.js
In this fix the magazine filter updates the URL and the `v2-article-cards block` content to reflect the filtering. The search result also is shown on the page without the need to open a new tab. In an article page, the filtering goes to the main Magazine page to show the results.
A time ago, the data grabbed from the metadata and stored in the search engine was transformed in lowercase, so in FE was needed to be retransform again. Now BE no longer does that so is not needed to retransform in FE again. That fixes issue #295
Added a languagePath checker to apply also the fix for the Canada site
#
Fix #294, #295
- After: …
=> FR: Enable article filter to update magazine page #294 #295

blocks/v2-custom-form/v2-custom-form.css, blocks/v2-custom-form/v2-custom-form.js
This Update adds a `Double Column` variant to _v2-Custom-Form_ Block. It's already added to the library as the list's last item variant
Fix #283
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/v2-2-columns-form-demo
- After: https://283-double-column-form--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/v2-2-columns-form-demo
Library link page (last form):
- Before: https://main--volvotrucks-ca--volvogroup.aem.page/block-library/blocks/v2-custom-form
- After: https://283-double-column-form--volvotrucks-ca--volvogroup.aem.page/block-library/blocks/v2-custom-form
Library item
- Before: https://main--volvotrucks-us--volvogroup.aem.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-custom-form&index=4
- After: …
=> FR: Double Column Variant Form for the MCAE - VT #283

blocks/v2-media-with-text/v2-media-with-text.css, styles/styles.css
the play button in media-with-text and the v2 hero now have placed in all viewports at the bottom. the mute button also will be at the bottom, over the play/pause one.
Fix #274
- Before: https://main--volvotrucks-us--volvogroup.aem.page/trucks/vnr-electric/
- After: https://274-pause-btn-mobile-position--volvotrucks-us--volvogroup.aem.page/trucks/vnr-electric/
=> Bug: Wrong placement of the video pause button across VT on mobile #274

scripts/scripts.js
Fix #169
- After: https://169-html-lang-settings--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- After: https://169-html-lang-settings--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://169-html-lang-settings--volvotrucks-mx--volvogroup.aem.page/
=> NFR: Language setting needs to be applied to all website - VT #169

blocks/search/autosuggest.js, scripts/search-api.js
Fix #149
- After: https://149-autosuggest-lang--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- After: https://149-autosuggest-lang--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://149-autosuggest-lang--volvotrucks-mx--volvogroup.aem.page/
=> NFR: FE language query standarization #149

blocks/v2-stories-carousel/v2-stories-carousel.js, scripts/services/magazine.service.js
Tags metadata is no longer taken into account, and it grabs the tags from the 3 other tag types, such as article-category, topic and truck. In the future, as soon as the a-category is moved to the topic row, then no more development will be needed because that value will be empty.
Added also a little bug that didn't remove the current article
#
#Fix #330
- Before: https://main--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-stories/cover-story-designed-to-change-everything/
- After: https://330-new-filter-logic--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-stories/cover-story-designed-to-change-everything/
Other markets:
Canada:
- Before: https://main--volvotrucks-ca--volvogroup.aem.page/en-ca/news-and-stories/volvo-trucks-stories/co …
=> CR: Update V2 Stories Carousel block filtering logic #330

.github/workflows/publish-notifier.yaml
Fix #89 
Test in GitHub action after publishing (or republishing) a page
This implementation uses a 3rd party email handler to send an email when the publish action triggers and its status is _failure_
- No Test URL
https://main--volvotrucks-us--volvogroup.aem.page/
unpublished, not implemented yet
=> Spike: Update GitHub Actions - Notifications (2 of 4) #89 

blocks/press-releases/press-releases.js, common/pagination/pagination.css
Fix #43 
- Before: https://main--volvotrucks-us--volvogroup.aem.page/news-and-stories/press-releases/
- After: https://43-press-releases-pagination--volvotrucks-us--volvogroup.aem.page/news-and-stories/press-releases/
=> FR: Adapting Press Releases to Use Pagination from Article Cards

blocks/v2-media-with-text/v2-media-with-text.css
Buttons are set consistently, and all video players are 16/9 aspect ratio.
#
Fix #204
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-media-with-text
- After: https://204-video-buttons-consistent--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-media-with-text
Library URL:
- Before: https://main--volvotrucks-us--volvogroup.aem.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-media-with-text&index=10
- After: https://204-video-buttons-consistent--volvotrucks-us--volvogroup.aem.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-media-with-text&index=10
Other markets:
Canada:
- Before: https://main--volvotrucks-ca--volvogroup.aem.page/block-library/blocks/v2-media-with-text …
=> Bug: V2 Media with Text - Ensure consistent play/pause/mute button styling and correct video aspect ratio. #204

blocks/magazine-articles/magazine-articles.js, blocks/press-releases/press-releases.css, blocks/press-releases/press-releases.js, placeholder.json, scripts/search-api.js, scripts/services/press-release.service.js
Fix #389
- After: https://389-press-releases--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada FR-CA:
- Before: https://main--volvotrucks-ca--volvogroup.aem.page/fr-ca/
- After: https://389-press-releases--volvotrucks-ca--volvogroup.aem.page/fr-ca/
Canada EN-CA:
- After: https://389-press-releases--volvotrucks-ca--volvogroup.aem.page/
=> NFR: FE WORK - implement press releases from query to opensearch #389

common/modal/modal.css
Fix #335 
- Before: https://main--volvotrucks-us--volvogroup.aem.page/trucks/all-new-vnr/#connectivity
- After: https://335-fix-spacing-in-connectivity--volvotrucks-us--volvogroup.aem.page/trucks/all-new-vnr/#connectivity
Note: It is tricky one so I applied the spacing only to content of modal. If you think there is better approach to fix this issue, do let me know.
=> Bug: MyTruck App Padding from Connectivity section

blocks/magazine-articles/magazine-articles.css, blocks/magazine-articles/magazine-articles.js, blocks/v2-article-cards/v2-article-cards.css, blocks/v2-article-cards/v2-article-cards.js, scripts/magazine-press.js, scripts/services/magazine.service.js
Fix #438
- Before: https://main--volvotrucks-us--volvogroup.aem.page/news-and-stories/
- After: https://438-mgz-query--volvotrucks-us--volvogroup.aem.page/news-and-stories/
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/shomps/magazine-articles
- After: https://438-mgz-query--volvotrucks-us--volvogroup.aem.page/drafts/shomps/magazine-articles
- After: https://438-mgz-query--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-stories/
*0 FEATURED*
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/shomps/article-cards/0-featured
- After: https://438-mgz-query--volvotrucks-us--volvogroup.aem.page/drafts/shomps/article-cards/0-fe …
=> FR: Extend limit of articles in magazine query #438

scripts/common.js, scripts/scripts.js
Changed the loading from the `loadLazy` function to the `loadEager` one. Now, loads just at the beginning without any waiting.
#
- After: https://452-header-loading-delay--volvotrucks-us--volvogroup.aem.page/
Disabled header:
- Before: https://main--volvotrucks-us--volvogroup.aem.page/trucks/vnr/truck-builder/
- After: https://452-header-loading-delay--volvotrucks-us--volvogroup.aem.page/trucks/vnr/truck-builder/
Other markets:
Canada:
- After: https://452-header-loading-delay--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://452-header-loading-delay--volvotrucks-mx--volvogroup.ae …
=> Bug: Delay in loading of header on homepage #452

blocks/v2-content-card/v2-content-card.css, blocks/v2-content-card/v2-content-card.js
Fix #470 
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/naga/v2-content-card
- After: https://470-v2-content-card-new-variant--volvotrucks-us--volvogroup.aem.page/drafts/naga/v2-content-card
Block Library:
- Before: https://main--volvotrucks-us--volvogroup.aem.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-content-card&index=2
- After: https://470-v2-content-card-new-variant--volvotrucks-us--volvogroup.aem.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-content-card&index=7
Please use variant `(with-button)` to test this in V2 content card component.  Also use link with bold styling in document to have a button in the page.
=> FR: New variant for the V2 Content Card block #470

blocks/v2-truck-lineup/v2-truck-lineup.css, blocks/v2-truck-lineup/v2-truck-lineup.js
In this update, the truck lineup has a new variant set in the metadata as a new _style_ because this is an autoblock and can't have a variants set as a regular block.
The variant is called `truck-lineup-buttons`
I also added the current default variant as a reference in the second pair of links
#
Fix #473
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/v2-truck-lineup-buttons
- After: https://473-update-truck-lineup--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/v2-truck-lineup-buttons
Current TAB version
- After: https://473-update-truck-lineup--volvotrucks-us--volvogroup.aem.page/
=> FR: Update V2 Truck Lineup block #473

blocks/v2-content-carousel/v2-content-carousel.css
Fix #507
- Before: https://main--volvotrucks-us--volvogroup.aem.page/campaign/vnl/
- After: https://507-bug-carousel--volvotrucks-us--volvogroup.aem.page/campaign/vnl/
Library:
- Before: https://main--volvotrucks-us--volvogroup.aem.page/tools/sidekick/library.html?theme=light&plugin=blocks&path=/block-library/blocks/v2-content-carousel&index=3
- After: https://507-bug-carousel--volvotrucks-us--volvogroup.aem.page/tools/sidekick/library.html?theme=light&plugin=blocks&path=/block-library/blocks/v2-content-carousel&index=3
Other markets:
Canada:
- After: https://507-bug-carousel--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: …
=> Bug: Large text size for Content Carousel #507

placeholder.json
Fix #493
- After: https://493-nhtsa-name--volvotrucks-us--volvogroup.aem.page/
=>  Transport Canada: Rename "Issue Date" to "NHTSA Issue Date“ [Volvo-English] #493

blocks/v2-hero/v2-hero.css, package-lock.json, package.json
Fix #<gh-issue-id>
- After: https://release-47--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- After: https://release-47--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://release-47--volvotrucks-mx--volvogroup.aem.page/
=> Release 47
